from django.db import models #type:ignore


class e_approval(models.Model):
    doc_status=models.CharField(max_length=100,blank=True,null=True)
    Document_no = models.CharField(max_length=500,primary_key=True)
    Department = models.CharField(max_length=100)
    Org_Unit = models.CharField(max_length=100)
    sub_category=models.CharField(max_length=100,blank=True, null=True)
    Category = models.CharField(max_length=100)
    Head_of_account = models.CharField(max_length=500,blank=True,null=True)
    remarks_Subject = models.CharField(max_length=100)
    remarks_Subject1 = models.CharField(max_length=100,blank=True,null=True)
    Priority = models.CharField(max_length=500)
    Tran_No = models.CharField(max_length=500,null=True)
    fin_commit = models.CharField(max_length=100)
    creator_name=models.CharField(max_length=100,blank=True,null=True)
    staff_id = models.CharField(max_length=10,blank=True,null=True)
    Tolerance = models.IntegerField(blank=True,null=True)
    Total_Value = models.IntegerField(blank=True,null=True)
    In_words = models.CharField(max_length=200,blank=True,null=True)
    creator=models.CharField(max_length=200,blank=True,null=True)
    creator_mail=models.CharField(max_length=200,blank=True,null=True)
    Attachment = models.FileField(upload_to='')
    date = models.DateField()
    Head_of_account=models.CharField(max_length=200,blank=True,null=True)
    Attachment_details = models.CharField(max_length=100,blank=True,null=True)
    Technician = models.CharField(max_length=100,blank=True,null=True)
    # office = models.CharField(max_length=100,blank=True,null=True)
    # Deputywarden = models.CharField(max_length=100,blank=True,null=True)
    # Transport_Incharge= models.CharField(max_length=100,blank=True,null=True)
    Staff_name=models.CharField(max_length=100,blank=True,null=True)
    Staff = models.CharField(max_length=100,blank=True,null=True)
    Staff_date = models.CharField(max_length=100,blank=True,null=True)
    HOD_name=models.CharField(max_length=100,blank=True,null=True)
    HOD = models.CharField(max_length=100,blank=True,null=True)
    HOD_date = models.CharField(max_length=100,blank=True,null=True)
    GM_name=models.CharField(max_length=100,blank=True,null=True)
    GM = models.CharField(max_length=100,blank=True,null=True)
    GM_date = models.CharField(max_length=100,blank=True,null=True)
    Vice_Principal_name=models.CharField(max_length=100,blank=True,null=True)
    Vice_Principal = models.CharField(max_length=100,blank=True,null=True)
    Vice_Principal_date = models.CharField(max_length=100,blank=True,null=True)
    Principal_name=models.CharField(max_length=100,blank=True,null=True)
    reject=models.CharField(max_length=100,blank=True,null=True)
    Principal = models.CharField(max_length=100,blank=True,null=True)
    Principal_date = models.CharField(max_length=100,blank=True,null=True)
    OfficeStaff_name=models.CharField(max_length=100,blank=True,null=True)
    OfficeStaff = models.CharField(max_length=100,blank=True,null=True)
    OfficeStaff_date = models.CharField(max_length=100,blank=True,null=True)
    Deputywarden_name=models.CharField(max_length=100,blank=True,null=True)
    Deputywarden = models.CharField(max_length=100,blank=True,null=True)
    Deputywarden_date = models.CharField(max_length=100,blank=True,null=True)
    Transport_Incharge_name=models.CharField(max_length=100,blank=True,null=True)
    Transport_Incharge = models.CharField(max_length=100,blank=True,null=True)
    Transport_Incharge_date = models.CharField(max_length=100,blank=True,null=True)

    def __str__(self):
        return self.Document_no

class status(models.Model):
    Document_no = models.CharField(max_length=200, primary_key=True)
    staff = models.CharField(max_length=100, blank=True, null=True)
    HOD = models.CharField(max_length=100,blank=True,null=True)
    GM = models.CharField(max_length=100,blank=True,null=True)
    Vice_Principal = models.CharField(max_length=100,blank=True,null=True)
    Principal = models.CharField(max_length=100,blank=True,null=True)
class User(models.Model):
    Name = models.CharField(max_length=100)
    user_name = models.CharField(max_length=100)
    staff_id = models.CharField(max_length=100)
    Department = models.CharField(max_length=100)
    Department_code=models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    Password = models.CharField(max_length=100)
    confirm_Password = models.CharField(max_length=100)



class auth_list(models.Model):
    Document_no = models.CharField(max_length=200, primary_key=True)

    staff = models.CharField(max_length=100, blank=True, null=True)
    staff_date = models.CharField(max_length=100, blank=True, null=True)
    staff_remarks = models.CharField(max_length=100, blank=True, null=True)
    staff_reason = models.CharField(max_length=100, blank=True, null=True)
    staff_clarification = models.CharField(max_length=100, blank=True, null=True)

    hod = models.CharField(max_length=100, blank=True, null=True)
    hod_date = models.CharField(max_length=100, blank=True, null=True)
    hod_remarks = models.CharField(max_length=100, blank=True, null=True)
    hod_reason = models.CharField(max_length=100, blank=True, null=True)
    hod_clarification = models.CharField(max_length=100, blank=True, null=True)
    
    gm = models.CharField(max_length=100, blank=True, null=True)
    gm_date = models.CharField(max_length=100, blank=True, null=True)
    gm_remarks = models.CharField(max_length=100, blank=True, null=True)
    gm_reason = models.CharField(max_length=100, blank=True, null=True)
    gm_clarification = models.CharField(max_length=100, blank=True, null=True)
    
    Vice_Principal = models.CharField(max_length=100, blank=True, null=True)
    Vice_Principal_date = models.CharField(max_length=100, blank=True, null=True)
    Vice_Principal_remarks = models.CharField(max_length=100, blank=True, null=True)
    Vice_Principal_reason = models.CharField(max_length=100, blank=True, null=True)
    Vice_Principal_clarification = models.CharField(max_length=100, blank=True, null=True)
    
    Principal = models.CharField(max_length=100, blank=True, null=True)
    Principal_date = models.CharField(max_length=100, blank=True, null=True)
    Principal_remarks = models.CharField(max_length=100, blank=True, null=True)
    Principal_reason = models.CharField(max_length=100, blank=True, null=True)
    Principal_clarification = models.CharField(max_length=100, blank=True, null=True)

class clarification(models.Model):
    Document_no = models.CharField(max_length=200, primary_key=True)
    remarks = models.CharField(max_length=500, blank=True, null=True)
    reroute_comments = models.CharField(max_length=500, blank=True, null=True)
    reroute_clarification = models.CharField(max_length=500, blank=True, null=True)


class auth_remarks(models.Model):
    Document_no = models.CharField(max_length=200, primary_key=True)
    auth_approval=models.CharField(max_length=100,blank=True, null=True)
    auth_remarks=models.CharField(max_length=100,blank=True, null=True)
    auth_reason=models.CharField(max_length=100,blank=True,null=True)

class doc_remarks(models.Model):
    Document_no = models.CharField(max_length=200, primary_key=True)
    doc_date_and_time = models.DateField(auto_now_add=True)
    doc_approval_id =models.CharField(max_length=20, blank=True,null=True)
    doc_applied_staff_id =models.CharField(max_length=20, blank=True,null=True)
    doc_subject=models.CharField(max_length=100, blank=True,null=True)
    doc_remarks=models.CharField(max_length=100, blank=True,null=True)
    doc_attachment=models.CharField(max_length=100,blank=True,null=True)
    doc_clarification_status=models.CharField(max_length=100,blank=True,null=True)
    doc_clarifictaions_reason=models.CharField(max_length=100,blank=True,null=True)

class clarification(models.Model):
    Document_no = models.CharField(max_length=200, primary_key=True)
    clarification_approval=models.CharField(max_length=500, blank=True, null=True)
    clarification_date_and_time = models.DateField(auto_now_add=True)
    clarification_remarks = models.CharField(max_length=500, blank=True, null=True)
    clarification_reroute_comments = models.CharField(max_length=500, blank=True, null=True)
    clarification_reroute_clarification = models.CharField(max_length=500, blank=True, null=True)
class allotment(models.Model):
    Department=models.CharField(max_length=100,blank=True, null=True)
    acyear=models.CharField(max_length=100,blank=True, null=True)
    capitalGoods=models.IntegerField( blank=True, null=True)
    academic=models.IntegerField( blank=True, null=True)
    rnd=models.IntegerField( blank=True, null=True)
    recurringItems=models.IntegerField( blank=True, null=True)
    coCurricular=models.IntegerField( blank=True, null=True)
    facultyCompetency=models.IntegerField( blank=True, null=True)
    trainingPlacement=models.IntegerField( blank=True, null=True)
    extraCurricular=models.IntegerField( blank=True, null=True)
    governanceAdmin=models.IntegerField( blank=True, null=True)
    generalAmenities=models.IntegerField( blank=True, null=True)
    others=models.IntegerField( blank=True, null=True)
    transport=models.IntegerField( blank=True, null=True)
    expenditure=models.IntegerField( blank=True, null=True)
    total_amount=models.IntegerField( blank=True, null=True)
    balance_amount=models.IntegerField( blank=True, null=True)
    allot_expenditure=models.IntegerField( blank=True, null=True)