# Generated by Django 5.0.4 on 2024-05-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='e_approval',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=100)),
                ('Org_Unit', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Sub_Category', models.CharField(max_length=100)),
                ('remarks_Subject', models.CharField(max_length=100)),
                ('Priority', models.CharField(max_length=100)),
                ('Tran_No', models.CharField(max_length=100)),
                ('fin_commit', models.CharField(max_length=100)),
                ('Tolerance', models.CharField(max_length=100)),
                ('Total_Value', models.CharField(max_length=100)),
                ('Attachment', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Attachment_details', models.CharField(blank=True, max_length=100, null=True)),
                ('Technician', models.CharField(blank=True, max_length=100, null=True)),
                ('HOD', models.CharField(blank=True, max_length=100, null=True)),
                ('GM', models.CharField(blank=True, max_length=100, null=True)),
                ('vise_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('conform_Password', models.CharField(max_length=100)),
            ],
        ),
    ]
