# Generated by Django 5.0.4 on 2024-05-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
