# Generated by Django 5.0.4 on 2024-05-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_e_approval_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='GM_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='HOD_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='principal_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='vise_principal_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
