# Generated by Django 4.2.5 on 2024-05-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_e_approval_gm_date_e_approval_hod_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_list',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hod', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_date', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_clarification', models.CharField(blank=True, max_length=100, null=True)),
                ('gm', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_date', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_clarification', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_principal_date', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_principal_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_principal_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_principal_clarification', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_date', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('principal_clarification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='auth_remarks',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('auth_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clarification',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clarification_approval', models.CharField(blank=True, max_length=500, null=True)),
                ('clarification_date_and_time', models.DateField(auto_now_add=True)),
                ('clarification_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('clarification_reroute_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('clarification_reroute_clarification', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doc_remarks',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('doc_date_and_time', models.DateField(auto_now_add=True)),
                ('doc_approval_id', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_applied_staff_id', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_attachment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vise_principal',
            new_name='vice_principal',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vise_principal_date',
            new_name='vice_principal_date',
        ),
        migrations.AddField(
            model_name='e_approval',
            name='In_words',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Spend_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='staff_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
