# Generated by Django 5.0.4 on 2024-05-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_e_approval_gm_date_e_approval_hod_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_list',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hod', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_date', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_clarification', models.CharField(blank=True, max_length=100, null=True)),
                ('gm', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_date', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('gm_clarification', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_prinicipal', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_prinicipal_date', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_prinicipal_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_prinicipal_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_prinicipal_clarification', models.CharField(blank=True, max_length=100, null=True)),
                ('prinicipal', models.CharField(blank=True, max_length=100, null=True)),
                ('prinicipal_date', models.CharField(blank=True, max_length=100, null=True)),
                ('prinicipal_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('prinicipal_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('prinicipal_clarification', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
