# Generated by Django 5.0.4 on 2024-05-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auth_list_auth_remarks_clarification_doc_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_list',
            name='lab_Incharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auth_list',
            name='lab_Incharge_clarification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auth_list',
            name='lab_Incharge_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auth_list',
            name='lab_Incharge_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auth_list',
            name='lab_Incharge_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='lab_Incharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='lab_Incharge_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
