# Generated by Django 5.0.4 on 2024-05-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auth_list_auth_remarks_clarification_doc_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_remarks',
            name='doc_clarification_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doc_remarks',
            name='doc_clarifictaions_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auth_list',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auth_remarks',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clarification',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doc_remarks',
            name='Document_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='Attachment',
            field=models.FileField(upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
