# Generated by Django 4.2.5 on 2024-05-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auth_list_auth_remarks_clarification_doc_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_remarks',
            name='Document_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
