# Generated by Django 5.0.4 on 2024-05-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auth_list_auth_remarks_clarification_doc_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='conform_Password',
            new_name='confirm_Password',
        ),
    ]
