# Generated by Django 5.0.4 on 2024-05-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auth_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_approval',
            old_name='vise_principal',
            new_name='vice_principal',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vise_principal_date',
            new_name='vice_principal_date',
        ),
    ]
