# Generated by Django 5.0.4 on 2024-06-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auth_list_staff_auth_list_staff_clarification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_remarks',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
