# Generated by Django 5.0.4 on 2024-05-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_vise_principal_e_approval_vice_principal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_list',
            old_name='prinicipal',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='prinicipal_clarification',
            new_name='principal_clarification',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='prinicipal_date',
            new_name='principal_date',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='prinicipal_reason',
            new_name='principal_reason',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='prinicipal_remarks',
            new_name='principal_remarks',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_prinicipal',
            new_name='vice_principal',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_prinicipal_clarification',
            new_name='vice_principal_clarification',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_prinicipal_date',
            new_name='vice_principal_date',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_prinicipal_reason',
            new_name='vice_principal_reason',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_prinicipal_remarks',
            new_name='vice_principal_remarks',
        ),
    ]
