# Generated by Django 4.2.5 on 2024-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_doc_remarks_document_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_remarks',
            name='doc_clafification_staues',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
