# Generated by Django 5.0.4 on 2024-05-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_conform_password_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
