# Generated by Django 5.0.4 on 2024-05-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_doc_remarks_doc_clarification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='Attachment',
            field=models.FileField(upload_to=''),
        ),
    ]
