# Generated by Django 4.2.5 on 2024-05-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_doc_remarks_doc_clafification_staues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc_remarks',
            old_name='doc_clafification_staues',
            new_name='doc_clafification_status',
        ),
    ]
