# Generated by Django 5.0.4 on 2024-06-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_doc_remarks_document_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='Tran_No',
            field=models.CharField(max_length=200),
        ),
    ]
