# Generated by Django 4.2.5 on 2024-05-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_e_approval_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_approval',
            name='Spend_type',
        ),
    ]
