# Generated by Django 5.0.4 on 2024-05-09 04:15

from django.db import migrations, models # type: ignore
 

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_rename_prinicipal_auth_list_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clarification',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('reroute_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('reroute_clarification', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
