# Generated by Django 5.0.6 on 2024-05-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_rename_prinicipal_auth_list_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_remarks',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('auth_approval', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clarification',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('clarification_approval', models.CharField(blank=True, max_length=500, null=True)),
                ('clarification_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('clarification_reroute_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('clarification_reroute_clarification', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doc_remarks',
            fields=[
                ('Document_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('doc_approval', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_attachment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Spend_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
