# Generated by Django 5.0.6 on 2024-05-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auth_remarks_clarification_doc_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='In_words',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doc_remarks',
            name='doc_remarks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doc_remarks',
            name='doc_subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='staff_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
