# Generated by Django 4.2.5 on 2024-05-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_doc_clafification_staues_doc_remarks_doc_clafification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc_remarks',
            old_name='doc_clafification_status',
            new_name='doc_clarification_status',
        ),
        migrations.AddField(
            model_name='doc_remarks',
            name='doc_clarifictaions_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
