# Generated by Django 5.0.4 on 2024-06-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_e_approval_tran_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Department_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
