# Generated by Django 5.0.4 on 2024-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_user_department_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('Document_no', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('staff', models.CharField(blank=True, max_length=100, null=True)),
                ('HOD', models.CharField(blank=True, max_length=100, null=True)),
                ('GM', models.CharField(blank=True, max_length=100, null=True)),
                ('vice_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Department_code',
            field=models.CharField(max_length=100),
        ),
    ]
