# Generated by Django 4.2.5 on 2024-05-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_doc_clafification_status_doc_remarks_doc_clarification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
