# Generated by Django 4.2.5 on 2024-05-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_e_approval_document_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_list',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auth_remarks',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clarification',
            name='Document_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
