# Generated by Django 5.0.4 on 2024-06-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_status_alter_user_department_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_approval',
            old_name='Sub_Category',
            new_name='Head_of_account',
        ),
    ]
