# Generated by Django 5.0.4 on 2024-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_rename_sub_category_e_approval_head_of_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='remarks_Subject1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
