# Generated by Django 4.2.5 on 2024-05-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_auth_list_document_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='Attachment',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
