# Generated by Django 5.0.4 on 2024-06-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_e_approval_remarks_subject1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='In_words',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
