# Generated by Django 5.0.4 on 2024-06-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_e_approval_in_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='In_words',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='Total_Value',
            field=models.IntegerField(),
        ),
    ]
