# Generated by Django 5.0.4 on 2024-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_e_approval_in_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='Total_Value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
