# Generated by Django 5.0.4 on 2024-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_e_approval_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='creator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
