# Generated by Django 5.0.4 on 2024-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_e_approval_gm_name_e_approval_hod_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_doc_create',
            fields=[
                ('Document_no', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=100)),
                ('Org_Unit', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Head_of_account', models.CharField(max_length=100)),
                ('remarks_Subject', models.CharField(max_length=100)),
                ('remarks_Subject1', models.CharField(blank=True, max_length=100, null=True)),
                ('Priority', models.CharField(max_length=100)),
                ('Tran_No', models.CharField(max_length=200)),
                ('fin_commit', models.CharField(max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=10, null=True)),
                ('Tolerance', models.CharField(max_length=100)),
                ('Total_Value', models.CharField(blank=True, max_length=100, null=True)),
                ('In_words', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.CharField(blank=True, max_length=200, null=True)),
                ('Attachment', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('Attachment_details', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
