# Generated by Django 5.0.4 on 2024-06-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_temp_doc_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_doc_create',
            name='Tran_No',
        ),
    ]
