# Generated by Django 5.0.4 on 2024-06-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_remove_temp_doc_create_tran_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='Attachment',
            new_name='temp_Attachment',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='Attachment_details',
            new_name='temp_Attachment_details',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='Category',
            new_name='temp_Category',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='Head_of_account',
            new_name='temp_Head_of_account',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='In_words',
            new_name='temp_In_words',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='Priority',
            new_name='temp_Priority',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='Tolerance',
            new_name='temp_Tolerance',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='Total_Value',
            new_name='temp_Total_Value',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='date',
            new_name='temp_date',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='fin_commit',
            new_name='temp_fin_commit',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='remarks_Subject',
            new_name='temp_remarks_Subject',
        ),
        migrations.RenameField(
            model_name='temp_doc_create',
            old_name='remarks_Subject1',
            new_name='temp_remarks_Subject1',
        ),
    ]
