# Generated by Django 5.0.4 on 2024-06-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_temp_doc_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp_doc_create',
        ),
        migrations.AddField(
            model_name='e_approval',
            name='doc_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
