# Generated by Django 5.0.4 on 2024-06-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_delete_temp_doc_create_e_approval_doc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='Head_of_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
