# Generated by Django 5.0.4 on 2024-07-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_alter_e_approval_head_of_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('temp_doc_status', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_Document_no', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('temp_Department', models.CharField(max_length=100)),
                ('temp_Org_Unit', models.CharField(max_length=100)),
                ('temp_Category', models.CharField(max_length=100)),
                ('temp_Head_of_account', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_remarks_Subject', models.CharField(max_length=100)),
                ('temp_remarks_Subject1', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_Priority', models.CharField(max_length=100)),
                ('temp_Tran_No', models.CharField(max_length=200)),
                ('temp_fin_commit', models.CharField(max_length=100)),
                ('temp_staff_id', models.CharField(blank=True, max_length=10, null=True)),
                ('temp_Tolerance', models.CharField(max_length=100)),
                ('temp_Total_Value', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_In_words', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_creator', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_Attachment', models.FileField(upload_to='')),
                ('temp_date', models.DateField()),
                ('temp_Attachment_details', models.CharField(blank=True, max_length=100, null=True)),
                ('temp_Technician', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
