# Generated by Django 5.0.4 on 2024-08-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.AddField(
            model_name='e_approval',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
