# Generated by Django 5.0.4 on 2024-08-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_delete_temp_e_approval_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='Tran_No',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
