# Generated by Django 5.0.4 on 2024-08-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_alter_e_approval_tran_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='creator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
