# Generated by Django 5.0.4 on 2024-08-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_alter_e_approval_tran_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('acyear', models.CharField(blank=True, max_length=100, null=True)),
                ('capitalGoods', models.CharField(blank=True, max_length=500, null=True)),
                ('academic', models.CharField(blank=True, max_length=500, null=True)),
                ('rnd', models.CharField(blank=True, max_length=500, null=True)),
                ('recurringItems', models.CharField(blank=True, max_length=500, null=True)),
                ('coCurricular', models.CharField(blank=True, max_length=500, null=True)),
                ('facultyCompetency', models.CharField(blank=True, max_length=500, null=True)),
                ('trainingPlacement', models.CharField(blank=True, max_length=500, null=True)),
                ('extraCurricular', models.CharField(blank=True, max_length=500, null=True)),
                ('governanceAdmin', models.CharField(blank=True, max_length=500, null=True)),
                ('generalAmenities', models.CharField(blank=True, max_length=500, null=True)),
                ('others', models.CharField(blank=True, max_length=500, null=True)),
                ('transport', models.CharField(blank=True, max_length=500, null=True)),
                ('expenditure', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal',
            new_name='Principal',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal_clarification',
            new_name='Principal_clarification',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal_date',
            new_name='Principal_date',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal_reason',
            new_name='Principal_reason',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal_remarks',
            new_name='Principal_remarks',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal',
            new_name='Vice_Principal',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal_clarification',
            new_name='Vice_Principal_clarification',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal_date',
            new_name='Vice_Principal_date',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal_reason',
            new_name='Vice_Principal_reason',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal_remarks',
            new_name='Vice_Principal_remarks',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='principal',
            new_name='Deputywarden',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='principal_date',
            new_name='Deputywarden_date',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='principal_name',
            new_name='Deputywarden_name',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vice_principal',
            new_name='OfficeStaff',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vice_principal_date',
            new_name='OfficeStaff_date',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vp_name',
            new_name='OfficeStaff_name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='principal',
            new_name='Principal',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='vice_principal',
            new_name='Vice_Principal',
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Principal_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Principal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Transport_Incharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Transport_Incharge_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Transport_Incharge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Vice_Principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Vice_Principal_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Vice_Principal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='creator_mail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='creator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='reject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='Head_of_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='Priority',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='Tolerance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='Total_Value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='e_approval',
            name='Tran_No',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
