# Generated by Django 5.0.4 on 2024-08-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_allotment_rename_principal_auth_list_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='capitalGoods',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='coCurricular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='expenditure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='extraCurricular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='facultyCompetency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='generalAmenities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='governanceAdmin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='others',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='recurringItems',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='rnd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='trainingPlacement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allotment',
            name='transport',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
