# Generated by Django 5.0.4 on 2024-08-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_e_approval_creator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='creator_mail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
