# Generated by Django 5.0.4 on 2024-08-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_allotment_total_amount_alter_allotment_capitalgoods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='balance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
