# Generated by Django 5.0.4 on 2024-08-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_e_approval_creator_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_approval',
            name='Tolerance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
