# Generated by Django 5.0.4 on 2024-08-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_allotment_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='academic',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
    ]
