# Generated by Django 5.0.4 on 2024-08-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_alter_e_approval_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='reject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
