# Generated by Django 5.0.4 on 2024-08-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_e_approval_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='Deputywarden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Deputywarden_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Deputywarden_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Transport_Incharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Transport_Incharge_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='Transport_Incharge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='office_data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='e_approval',
            name='office_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
