# Generated by Django 5.0.4 on 2024-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_alter_allotment_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='academic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
