# Generated by Django 5.0.4 on 2024-08-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_alter_allotment_academic'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='allot_expenditure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
