# Generated by Django 5.0.4 on 2024-08-15 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_e_approval_deputywarden_e_approval_deputywarden_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal',
            new_name='Principal',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal_clarification',
            new_name='Principal_clarification',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal_date',
            new_name='Principal_date',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal_reason',
            new_name='Principal_reason',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='principal_remarks',
            new_name='Principal_remarks',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal',
            new_name='Vice_Principal',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal_clarification',
            new_name='Vice_Principal_clarification',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal_date',
            new_name='Vice_Principal_date',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal_reason',
            new_name='Vice_Principal_reason',
        ),
        migrations.RenameField(
            model_name='auth_list',
            old_name='vice_principal_remarks',
            new_name='Vice_Principal_remarks',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='office',
            new_name='OfficeStaff',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='office_data',
            new_name='OfficeStaff_data',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='office_name',
            new_name='OfficeStaff_name',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='principal',
            new_name='Principal',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='principal_date',
            new_name='Principal_date',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='principal_name',
            new_name='Principal_name',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vice_principal',
            new_name='Vice_Principal',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vice_principal_date',
            new_name='Vice_Principal_date',
        ),
        migrations.RenameField(
            model_name='e_approval',
            old_name='vp_name',
            new_name='Vice_Principal_name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='principal',
            new_name='Principal',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='vice_principal',
            new_name='Vice_Principal',
        ),
    ]
