# Generated by Django 5.0.4 on 2024-08-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_rename_principal_auth_list_principal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e_approval',
            old_name='OfficeStaff_data',
            new_name='OfficeStaff_date',
        ),
    ]
