# Generated by Django 5.0.4 on 2024-08-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_allotment_allot_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_approval',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
