# Generated by Django 5.0.4 on 2024-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_e_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_user_verification',
            fields=[
                ('staff_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
