# Generated by Django 5.0.4 on 2024-08-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_new_user_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('dept_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=500)),
            ],
        ),
    ]
