# Generated by Django 5.0.4 on 2024-08-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user_verification',
            name='dept_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
